trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: terraform_plan
  jobs:
  - job: terraform_plan
    steps:
    - script: |
        terraform init
        terraform plan
      displayName: 'Terraform Plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/src'
  - job: terraform_apply
    dependsOn: terraform_plan
    steps:
    - script: |
        terraform apply -auto-approve
      displayName: 'Terraform Apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/src'
