trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- displayName: 'Terraform Plan Stage'
  stage: terraform_plan
  jobs:
  - displayName: 'Terraform Plan Job'
    job: terraform_plan
    steps:
    - displayName: 'Terraform Plan Step'
      script: |
        cd src
        terraform init
        terraform plan -out=tfplan

- displayName: 'Terraform Apply Stage'
  stage: terraform_apply
  dependsOn: terraform_plan
  jobs:
  - displayName: 'Terraform Apply Job'
    job: terraform_apply
    steps:
    - displayName: 'Terraform Apply Step'
      script: |
        cd src
        terraform apply -auto-approve tfplan

