trigger:
- main

variables:
- group: pipeline-variables

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: initialize
  jobs:
  - job: terraform
    steps:
    - script: |
        terraform init
        terraform plan
      displayName: 'Terraform Plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/src'
      env:
        ARM_ACCESS_KEY: "$(REMOTE-STATE-STORAGE-CONNECTION-STRING)"
    - script: |
        terraform apply -auto-approve
      displayName: 'Terraform Apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/src'
      env:
        ARM_ACCESS_KEY: "$(REMOTE-STATE-STORAGE-CONNECTION-STRING)"
