trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: terraform_plan
  jobs:
  - job: terraform_plan
    steps:
    - displayName: 'Terraform Plan Step'
      script: |
        cd src
        terraform init
        terraform plan -out=tfplan

- stage: terraform_apply
  dependsOn: terraform_plan
  jobs:
  - job: terraform_apply
    steps:
    - displayName: 'Terraform Apply Step'
      script: |
        cd src
        terraform apply -auto-approve tfplan

