trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: terraform_plan
  jobs:
  - job: terraform_plan
    steps:
    - script: |
        terraform init
        terraform plan -out=tfplan
      displayName: 'Terraform Plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/src'

- stage: terraform_apply
  dependsOn: terraform_plan
  jobs:
  - job: terraform_apply
    steps:
    - script: |
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/src'
